name: size-limit-action
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1.3.2
        with:
          github_token: ${{ secrets.TOKEN }}
